import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Simple Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const header = (
    <header>
      <div>
        <h1 className="mx-auto text-3xl text-center font-bold">Welcome To My Blog</h1>
        <br/>
      </div>
    </header>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <br/>
        {header}
        {children}
      </body>
    </html>
  );
}
